# apps/vaultwarden/app-config.yaml
# 整合的应用配置文件，包含 ArgoCD 控制配置和 Kubernetes ConfigMap
#
# 文件结构说明：
# 1. argocd: 控制 ArgoCD ApplicationSet 行为（应用启用状态、同步策略等）
# 2. configMap: Kubernetes ConfigMap 资源，为应用 Pod 提供运行时配置
#
# 使用方式：
# - 修改 argocd 部分控制应用的部署和同步行为
# - 修改 configMap.data 部分更新应用的运行时配置
# - 提交到 Git 后 ArgoCD 自动同步

# ArgoCD 控制配置 - 控制 ApplicationSet 行为
argocd:
  metadata:
    name: "vaultwarden"
    description: "Bitwarden compatible password manager"
    category: "security"
    owner: "security-team"
    version: "1.0.0"

  deployment:
    enabled: false
    environments:
      prod:
        enabled: false
        autoSync: false
        prune: true
        selfHeal: false
      dev:
        enabled: true
        autoSync: true
        prune: true
        selfHeal: true
      staging:
        enabled: false
        autoSync: false
        prune: true
        selfHeal: false

  configuration:
    namespace: "vaultwarden"
    project: "default"
    syncOptions:
      - "CreateNamespace=true"
      - "PruneLast=true"
      - "ApplyOutOfSyncOnly=true"
      - "ServerSideApply=true"
      - "Validate=true"
    retryLimit: 2

---
# Kubernetes ConfigMap 资源 - 为应用 Pod 提供配置数据
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-app-config
  namespace: vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/part-of: k3s-cluster
    app.kubernetes.io/component: config
  annotations:
    app.kubernetes.io/description: "Configuration data for Vaultwarden password manager"

data:
  # 应用基本配置
  APP_NAME: "vaultwarden"
  APP_VERSION: "1.0.0"

  # Vaultwarden 特定配置
  ROCKET_PORT: "80"
  ROCKET_ADDRESS: "0.0.0.0"

  # 数据存储配置
  DATA_FOLDER: "/data"

  # 功能配置
  SIGNUPS_ALLOWED: "false"
  INVITATIONS_ALLOWED: "true"
  SHOW_PASSWORD_HINT: "false"

  # 安全配置
  DISABLE_ADMIN_TOKEN: "false"
  REQUIRE_DEVICE_EMAIL: "true"

  # 日志配置
  LOG_LEVEL: "warn"
  EXTENDED_LOGGING: "true"
