# 哪吒面板核心部署文件
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nezha-dashboard
  labels:
    app.kubernetes.io/name: nezha
    app.kubernetes.io/component: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nezha-dashboard
  template:
    metadata:
      labels:
        app: nezha-dashboard
        app.kubernetes.io/name: nezha
        app.kubernetes.io/component: dashboard
    spec:
      containers:
        - name: nezha-dashboard
          image: ghcr.io/nezhahq/nezha:latest
          ports:
            - name: http
              containerPort: 8008
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /dashboard/data
          # 环境变量配置
          env:
            - name: TZ
              value: "Asia/Shanghai"
          # 健康检查
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # 资源限制
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          # 移除安全上下文限制，让容器使用默认配置
          # securityContext 暂时注释掉，让哪吒面板使用默认权限运行
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nezha-data-pvc
      # Pod 安全上下文
      securityContext:
        fsGroup: 1000
      # 重启策略
      restartPolicy: Always
