# apps/monitoring/app-config.yaml
# 整合的应用配置文件，包含 ArgoCD 控制配置和 Kubernetes ConfigMap
#
# 文件结构说明：
# 1. argocd: 控制 ArgoCD ApplicationSet 行为（应用启用状态、同步策略等）
# 2. configMap: Kubernetes ConfigMap 资源，为应用 Pod 提供运行时配置
#
# 使用方式：
# - 修改 argocd 部分控制应用的部署和同步行为
# - 修改 configMap.data 部分更新应用的运行时配置
# - 提交到 Git 后 ArgoCD 自动同步
#
# 注意：此应用当前被禁用，配置仅作为示例保留

# ArgoCD 控制配置 - 控制 ApplicationSet 行为
argocd:
  metadata:
    name: "monitoring"
    description: "Complete monitoring stack with Prometheus, Grafana, and AlertManager"
    category: "observability"
    owner: "platform-team"
    version: "1.0.0"

  deployment:
    enabled: false
    environments:
      prod:
        enabled: false
        autoSync: false
        prune: true
        selfHeal: false
      dev:
        enabled: false
        autoSync: false
        prune: true
        selfHeal: false
      staging:
        enabled: false
        autoSync: false
        prune: true
        selfHeal: false

  configuration:
    namespace: "monitoring"
    project: "default"
    syncOptions:
      - "CreateNamespace=true"
      - "PruneLast=true"
      - "ApplyOutOfSyncOnly=true"
      - "ServerSideApply=true"
      - "SkipDryRunOnMissingResource=true"
    retryLimit: 2

---
# Kubernetes ConfigMap 资源 - 为应用 Pod 提供配置数据
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-app-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: k3s-cluster
    app.kubernetes.io/component: config
  annotations:
    app.kubernetes.io/description: "Configuration data for monitoring stack (currently disabled)"

data:
  # 应用基本配置
  APP_NAME: "monitoring"
  APP_VERSION: "1.0.0"

  # Prometheus 配置
  PROMETHEUS_RETENTION: "30d"
  PROMETHEUS_SCRAPE_INTERVAL: "30s"
  PROMETHEUS_EVALUATION_INTERVAL: "30s"

  # Grafana 配置
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_THEME: "dark"
  GRAFANA_TIMEZONE: "Asia/Shanghai"

  # AlertManager 配置
  ALERTMANAGER_RETENTION: "120h"

  # 存储配置
  DATA_RETENTION_POLICY: "30d"

  # 功能开关
  ENABLE_PROMETHEUS: "true"
  ENABLE_GRAFANA: "true"
  ENABLE_ALERTMANAGER: "true"
