# 生产环境 Vault Deployment 补丁
# 为生产环境优化资源配置和安全设置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
spec:
  template:
    spec:
      containers:
        - name: vault
          # 生产环境资源配置
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          
          # 生产环境变量
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_API_ADDR
              value: "https://vault.liuovo.com"  # 生产环境外部地址
            - name: VAULT_CLUSTER_ADDR
              value: "http://0.0.0.0:8201"
            - name: VAULT_CONFIG_DIR
              value: "/vault/config"
            - name: VAULT_DATA_DIR
              value: "/vault/data"
            - name: VAULT_LOG_LEVEL
              value: "WARN"  # 生产环境降低日志级别
            - name: VAULT_LOG_FORMAT
              value: "json"  # 生产环境使用 JSON 格式日志
          
          # 生产环境健康检查配置
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: http
              scheme: HTTP
            initialDelaySeconds: 60  # 生产环境增加初始延迟
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5  # 增加失败容忍度
          
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
