# HashiCorp Vault 生产环境 Kustomization
# 加载基础配置并应用生产环境特定的覆盖
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vault-prod
  annotations:
    config.kubernetes.io/local-config: "true"

# 指向基础配置和添加生产环境特有资源
resources:
  - ../../base
  - ingress.yaml

# 部署到 vault 命名空间
namespace: vault

# 应用生产环境补丁
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: vault

# 生产环境特定标签
commonLabels:
  environment: prod
  tier: production
  app.kubernetes.io/environment: prod

# 生产环境注解
commonAnnotations:
  deployment.kubernetes.io/environment: "production"
  vault.hashicorp.com/environment: "prod"
  config.kubernetes.io/origin: "vault-prod"

# 镜像配置（可选：固定版本）
images:
  - name: hashicorp/vault
    newTag: "1.20.0"

# 配置生成器（可选：为生产环境生成特定配置）
# configMapGenerator:
# - name: vault-prod-config
#   files:
#   - vault-prod.hcl
#   options:
#     disableNameSuffixHash: true
