# apps/uptime-kuma/app-config.yaml
# 整合的应用配置文件，包含 ArgoCD 控制配置和 Kubernetes ConfigMap
#
# 文件结构说明：
# 1. argocd: 控制 ArgoCD ApplicationSet 行为（应用启用状态、同步策略等）
# 2. configMap: Kubernetes ConfigMap 资源，为应用 Pod 提供运行时配置
#
# 使用方式：
# - 修改 argocd 部分控制应用的部署和同步行为
# - 修改 configMap.data 部分更新应用的运行时配置
# - 提交到 Git 后 ArgoCD 自动同步

# ArgoCD 控制配置 - 控制 ApplicationSet 行为
argocd:
  metadata:
    name: "uptime-kuma"
    description: "Service monitoring and uptime tracking application"
    category: "monitoring"
    owner: "platform-team"
    version: "1.0.0"

  deployment:
    enabled: true
    environments:
      prod:
        enabled: true
        autoSync: true
        prune: true
        selfHeal: true
      dev:
        enabled: false
        autoSync: true
        prune: true
        selfHeal: true
      staging:
        enabled: false
        autoSync: false
        prune: true
        selfHeal: false

  configuration:
    namespace: "uptime-kuma"
    project: "default"
    syncOptions:
      - "CreateNamespace=true"
      - "PruneLast=true"
      - "ApplyOutOfSyncOnly=true"
      - "ServerSideApply=true"
    retryLimit: 3

---
# Kubernetes ConfigMap 资源 - 为应用 Pod 提供配置数据
apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-kuma-app-config
  namespace: uptime-kuma
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/part-of: k3s-cluster
    app.kubernetes.io/component: config
  annotations:
    app.kubernetes.io/description: "Configuration data for Uptime Kuma application"

data:
  # 应用基本信息 - 可被应用 Pod 读取
  APP_NAME: "uptime-kuma"
  APP_DESCRIPTION: "Service monitoring and uptime tracking application"
  APP_VERSION: "1.0.0"

  # 应用运行时配置
  LOG_LEVEL: "info"
  NODE_ENV: "production"

  # 网络配置
  PORT: "3001"
  HOST: "0.0.0.0"

  # 数据存储配置
  DATA_DIR: "/app/data"

  # 功能开关
  ENABLE_NOTIFICATIONS: "true"
  ENABLE_METRICS: "false"
