# argocd/applicationset.yaml
# 基于整合配置文件的 ApplicationSet - GitOps 最佳实践
# 使用 Selector 过滤器实现精确的应用生成控制
# 纯配置驱动，无需脚本工具，适合 Windows 开发环境
#
# 实现方案：使用启用标记文件的约定
# 1. 在每个启用的应用环境目录中创建 .enabled 标记文件
# 2. 使用 Git 文件生成器发现这些标记文件
# 3. 通过 Selector 过滤器只生成有标记文件的应用
# 4. 实现真正的精确控制，未启用的应用完全不会在 ArgoCD 中生成

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: config-driven-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: config-driven-apps
    app.kubernetes.io/part-of: argocd
    gitops.argoproj.io/type: config-driven
  annotations:
    gitops.argoproj.io/description: "Configuration-driven ApplicationSet with Selector filtering"

spec:
  # 启用 Go 模板支持
  goTemplate: true

  # 使用 Git 文件生成器发现启用标记文件，实现精确的 Selector 过滤
  generators:
  - git:
      repoURL: https://github.com/liuc-c/k3s-cluster-argocd.git
      revision: HEAD
      files:
      # 发现启用标记文件：只有启用的应用环境才会有这些文件
      - path: "apps/*/.enabled-*"
      requeueAfterSeconds: 180

  template:
    metadata:
      # 从启用标记文件解析应用名称和环境
      # 文件格式：apps/app-name/.enabled-environment
      # 从路径 apps/uptime-kuma/.enabled-prod 中提取 uptime-kuma 和 prod
      name: '{{.path.path | dir | base}}-{{.path.filename | trimPrefix ".enabled-"}}'
      namespace: argocd

      # 标签系统
      labels:
        # 基础管理标签
        app.kubernetes.io/managed-by: applicationset
        app.kubernetes.io/name: '{{.path.path | dir | base}}'
        app.kubernetes.io/environment: '{{.path.filename | trimPrefix ".enabled-"}}'
        app.kubernetes.io/part-of: k3s-cluster

        # 启用状态标签
        gitops.argoproj.io/enabled: "true"
        gitops.argoproj.io/controlled-by: "selector-filter"

      # 注解
      annotations:
        gitops.argoproj.io/enabled-file: '{{.path.path}}'
        gitops.argoproj.io/app-name: '{{.path.path | dir | base}}'
        gitops.argoproj.io/environment: '{{.path.filename | trimPrefix ".enabled-"}}'
        argocd.argoproj.io/managed-by: config-driven-apps

      # 资源清理控制
      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: default

      # 源配置：根据启用标记文件构建应用路径
      source:
        repoURL: https://github.com/liuc-c/k3s-cluster-argocd.git
        # 构建路径：apps/app-name/overlays/environment 或 apps/app-name/environment
        path: 'apps/{{.path.path | dir | base}}/overlays/{{.path.filename | trimPrefix ".enabled-"}}'
        targetRevision: HEAD

        # Kustomize 配置
        kustomize:
          commonLabels:
            app.kubernetes.io/managed-by: argocd
            gitops.argoproj.io/environment: '{{.path.filename | trimPrefix ".enabled-"}}'
            gitops.argoproj.io/config-driven: "true"
          commonAnnotations:
            gitops.argoproj.io/enabled-file: '{{.path.path}}'

      # 目标配置：使用应用名称作为命名空间
      destination:
        name: in-cluster
        namespace: '{{index .path 1}}'

      # 同步策略：启用的应用使用自动同步
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false

        # 同步选项
        syncOptions:
        - "CreateNamespace=true"
        - "PruneLast=true"
        - "ApplyOutOfSyncOnly=true"
        - "ServerSideApply=true"

        # 重试策略
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s

      # 忽略差异配置
      ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
        - /spec/replicas
      - group: ""
        kind: Service
        jsonPointers:
        - /spec/clusterIP

      revisionHistoryLimit: 10

  # ApplicationSet 同步策略
  syncPolicy:
    preserveResourcesOnDeletion: false
    applicationsSync: create-update
