# 这个资源定义了应用的命名空间，会被 overlay 中的 namespace 字段覆盖
apiVersion: v1
kind: Namespace
metadata:
  name: uptime-kuma
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/component: namespace
