# ArgoCD ConfigMap 补丁 - 集成 Vault Plugin
# 为 ArgoCD 添加 Vault Plugin 支持
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: config
data:
  # 保持现有的 Kustomize Helm 支持
  kustomize.buildOptions: "--enable-helm"
  
  # 配置 Vault Plugin
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
    - name: argocd-vault-plugin-helm
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME . | argocd-vault-plugin generate -"]
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . | argocd-vault-plugin generate -"]
  
  # Vault Plugin 全局配置
  vault.server: "http://vault.vault.svc.cluster.local:8200"
  vault.auth.method: "kubernetes"
  vault.auth.kubernetes.role: "argocd"
  vault.auth.kubernetes.mount: "kubernetes"
  
  # 可选：配置 Vault 命名空间（如果使用 Vault Enterprise）
  # vault.namespace: "admin"
  
  # 可选：配置 TLS（如果 Vault 启用了 TLS）
  # vault.tls.skip.verify: "false"
  # vault.tls.cert.path: "/etc/ssl/certs/vault.crt"
