# ArgoCD Vault Plugin RBAC 配置
# 为 ArgoCD 提供访问 Vault 所需的权限

---
# ServiceAccount for ArgoCD Repo Server (如果不存在)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-repo-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: repo-server
automountServiceAccountToken: true

---
# ClusterRole - ArgoCD 访问 Vault 所需的权限
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-vault-plugin
  labels:
    app.kubernetes.io/name: argocd-vault-plugin
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: rbac
rules:
  # TokenReview 权限（Vault Kubernetes Auth 需要）
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  
  # SubjectAccessReview 权限
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  
  # ServiceAccount 权限
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-vault-plugin
  labels:
    app.kubernetes.io/name: argocd-vault-plugin
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-vault-plugin
subjects:
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: argocd

---
# Role - ArgoCD 命名空间内的权限
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-vault-plugin
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-vault-plugin
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: rbac
rules:
  # Secret 权限（用于存储 Vault tokens）
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch"]
  
  # ConfigMap 权限
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]

---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-vault-plugin
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-vault-plugin
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-vault-plugin
subjects:
  - kind: ServiceAccount
    name: argocd-repo-server
    namespace: argocd
