# ArgoCD Repo Server 补丁 - 集成 Vault Plugin
# 为 ArgoCD Repo Server 添加 Vault Plugin 二进制文件和配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      # 添加 init 容器来下载 Vault Plugin
      initContainers:
        - name: download-tools
          image: alpine:3.18
          command: [sh, -c]
          args:
            - |
              # 下载 argocd-vault-plugin
              wget -O argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v1.18.1/argocd-vault-plugin_1.18.1_linux_amd64
              chmod +x argocd-vault-plugin
              mv argocd-vault-plugin /custom-tools/
              
              # 验证下载
              /custom-tools/argocd-vault-plugin version
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
      
      containers:
        - name: argocd-repo-server
          # 添加 Vault Plugin 到 PATH
          env:
            - name: PATH
              value: /custom-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            
            # Vault 配置环境变量
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
            - name: AVP_TYPE
              value: "vault"
            - name: AVP_AUTH_TYPE
              value: "k8s"
            - name: AVP_K8S_ROLE
              value: "argocd"
            - name: AVP_K8S_MOUNT_PATH
              value: "auth/kubernetes"
            
            # 可选：Vault 命名空间（Vault Enterprise）
            # - name: VAULT_NAMESPACE
            #   value: "admin"
            
            # 可选：TLS 配置
            # - name: VAULT_SKIP_VERIFY
            #   value: "true"
          
          # 挂载自定义工具
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
            - mountPath: /usr/local/bin/argocd-vault-plugin
              name: custom-tools
              subPath: argocd-vault-plugin
          
          # 安全上下文
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      
      # 添加存储卷
      volumes:
        - name: custom-tools
          emptyDir: {}
      
      # 服务账户
      serviceAccountName: argocd-repo-server
