# HashiCorp Vault 配置文件
# 包含 Vault 服务器的核心配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: vault-system
data:
  vault.hcl: |
    # Vault 服务器配置文件
    
    # 存储后端配置 - 使用文件存储
    storage "file" {
      path = "/vault/data"
    }
    
    # 监听器配置
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = true  # 在集群内部禁用 TLS，通过 Ingress 处理 TLS
    }
    
    # API 地址配置
    api_addr = "http://0.0.0.0:8200"
    cluster_addr = "http://0.0.0.0:8201"
    
    # UI 配置
    ui = true
    
    # 日志级别
    log_level = "INFO"
    
    # 禁用 mlock（在容器环境中通常需要）
    # 注意：Vault 1.20.0+ 要求明确设置此值
    disable_mlock = true
    
    # 集群配置（单节点模式）
    cluster_name = "vault-cluster"
    
    # 审计日志配置（可选）
    # audit {
    #   file {
    #     file_path = "/vault/logs/audit.log"
    #   }
    # }
