# HashiCorp Vault 配置文件
# 包含 Vault 服务器的核心配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: vault-system
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    api_addr = "http://127.0.0.1:8200"
    ui = true
    disable_mlock = true
