# HashiCorp Vault 核心部署文件
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: vault-system
spec:
  replicas: 1  # 单节点模式，生产环境建议使用 HA 模式
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
        app.kubernetes.io/name: vault
        app.kubernetes.io/component: server
    spec:
      # 安全上下文
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
        # 确保挂载的卷有正确的权限
        fsGroupChangePolicy: "OnRootMismatch"
      
      containers:
        - name: vault
          image: hashicorp/vault:1.20.0
          imagePullPolicy: IfNotPresent
          
          # 容器安全上下文
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false  # Vault 需要写入临时文件
            capabilities:
              drop:
                - ALL
              add:
                - IPC_LOCK  # Vault 需要 IPC_LOCK 能力
          
          # 端口配置
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
            - name: cluster
              containerPort: 8201
              protocol: TCP
          
          # 环境变量
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
            - name: VAULT_API_ADDR
              value: "http://0.0.0.0:8200"
            - name: VAULT_CLUSTER_ADDR
              value: "http://0.0.0.0:8201"
            - name: VAULT_CONFIG_DIR
              value: "/vault/config"
            - name: VAULT_DATA_DIR
              value: "/vault/data"
            - name: VAULT_LOG_LEVEL
              value: "INFO"
          
          # 启动命令
          command:
            - "vault"
          args:
            - "server"
            - "-config=/vault/config/vault.hcl"
          
          # 存储卷挂载
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
              readOnly: true
            - name: vault-data
              mountPath: /vault/data
            - name: tmp
              mountPath: /tmp
          
          # 健康检查
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          
          # 资源限制
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      
      # 存储卷定义
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
            defaultMode: 0644
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-data-pvc
        - name: tmp
          emptyDir: {}
      
      # 服务账户
      serviceAccountName: vault
      
      # 节点选择器（可选）
      # nodeSelector:
      #   vault: "true"
      
      # 容忍度（可选）
      # tolerations:
      # - key: "vault"
      #   operator: "Equal"
      #   value: "true"
      #   effect: "NoSchedule"
