# HashiCorp Vault 基础配置 Kustomization
# 定义 Vault 应用的所有基础资源
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: vault-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - vault-init-job.yaml
  - vault-unseal-job.yaml
  - vault-backup-cronjob.yaml

# 通用标签
commonLabels:
  app.kubernetes.io/name: vault
  app.kubernetes.io/instance: vault
  app.kubernetes.io/version: "1.20.0"
  app.kubernetes.io/managed-by: kustomize

# 通用注解
commonAnnotations:
  vault.hashicorp.com/managed-by: "kustomize"
  config.kubernetes.io/origin: "vault-base"
